"""
Find all muJava pre-compiled Java files.
For each Java file, parse method_list.txt and mutation_log.txt.
"""
import numpy as np
import pandas as pd
import os
import re


class ParseLog(object):
    def __init__(self, file_dirs):
        self.sep = "####"
        self.endswith = ".class"
        self.file_dirs = self.to_long_path(file_dirs)
        self.output_dir = ".\\dataset\\"

        # self.required_files = ["ast.jsonl", "cfg.jsonl", "dfg.jsonl", "manifest.json"]
        self.required_files = ["output.json", "IR.jimple"]

        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def find_java_files(self, directory, endswith=".java"):
        """
        Recursively find files under the given directory with the specified suffix.
        """
        j_files = []
        for root, dirs, files in os.walk(directory):
            for file in files:
                if file.endswith(endswith):
                    j_files.append(os.path.join(root, file))
        return j_files

    def parse_log(self):
        """
        Collect statistics for the number of methods and mutants generated by muJava.
        :return: (method_df, mutant_df)
        """

        method_dfs = pd.DataFrame()
        mutant_dfs = pd.DataFrame()

        for root, dirs, files in os.walk(self.file_dirs):
            for file in files:
                if os.path.basename(file) not in ["method_list.txt", "mutation_log.txt"]:
                    continue

                # Find all compiled Java class files
                path_arr = []

                java_files = self.find_java_files(root, endswith=self.endswith)
                if not java_files:
                    continue
                for f in java_files:
                    f = f
                    method = f.split("\\")[-3]
                    operator = f.split("\\")[-2]
                    project = str(f.split("\\result\\")[0]).split("\\")[-1]
                    package = str(f.split("\\result\\")[1]).split("\\")[0]

                    # Parsing only by path can be error-prone; here we rely primarily on the class name in mutation_log
                    class_name = str(f.split("\\")[-1]).split(self.endswith)[0]

                    # file_path = f.split("\\result\\")[1]
                    file_path = os.path.abspath(f)
                    path_arr += [[operator, method, class_name, package, project, file_path]]
                cols = ["operator", "method", "class_f", "package", "project", "file_path"]
                path_df = pd.DataFrame(path_arr, columns=cols)
                file = os.path.join(root, file)
                print(file)

                # Clean method_list.txt log
                if os.path.basename(file) == "method_list.txt":
                    columns = ["method"]
                    method_df = self.get_df(file, columns)
                    tmp = self.clean_method(path_df, method_df, file)
                    method_dfs = pd.concat([method_dfs, tmp], axis=0)

                # Clean mutation_log.txt log
                if os.path.basename(file) == "mutation_log.txt":
                    columns = ["operator", "line", "method", "class", "class_f", "mutation_statement"]
                    mutant_df = self.get_df(file, columns)
                    tmp = self.clean_mutants(path_df, mutant_df, file)
                    mutant_dfs = pd.concat([mutant_dfs, tmp], axis=0)

        return method_dfs, mutant_dfs

    def clean_method(self, path_df, method_df, file_path, rewrite=False):
        """
        Clean the method log by deduplicating methods and merging with path information.
        Optionally rewrite a cleaned method_list file.
        """
        path_df = path_df.drop_duplicates(subset=['method']).reset_index(drop=True)
        result = pd.merge(method_df, path_df, on=['method'], how='inner')

        if rewrite:
            write_arr = result[["method"]].values
            file_path = file_path.replace("method_list.txt", "method_list_clean.txt")
            with open(file_path, "w", encoding="utf-8") as f:
                for row in write_arr:
                    f.write(self.sep.join(row) + "\n")

        return result

    def clean_mutants(self, path_df, log_df, file_path, rewrite=False):
        """
        Clean the mutant log by merging log entries with path information.
        Optionally rewrite a cleaned mutation_log file.
        """
        result = pd.merge(log_df, path_df, on=['method', 'operator', "class_f"], how='inner')

        if rewrite:
            write_arr = result[["operator", "line", "method", "mutation_statement"]].values
            file_path = file_path.replace("mutation_log.txt", "mutation_log_clean.txt")
            with open(file_path, "w", encoding="utf-8") as f:
                for row in write_arr:
                    f.write(self.sep.join(row) + "\n")

        return result

    def get_df(self, file, columns):
        """
        Read a log file and split each line by the separator into a DataFrame.
        """
        contents = []
        with open(file, 'r', encoding='utf-8') as f:
            for line in f:
                contents += [line.strip()]

        data_log = []
        for line in contents:
            data_log += [re.split(self.sep, line)]
        return pd.DataFrame(data_log, columns=columns)

    def split_and_export_to_excel(self, df, base_filename, chunk_size=150000):
        """
        Split a large DataFrame into multiple chunks and export each chunk to an Excel file.
        """
        total_rows = len(df)
        num_chunks = (total_rows + chunk_size - 1) // chunk_size

        for i in range(num_chunks):
            start = i * chunk_size
            end = min(start + chunk_size, total_rows)
            chunk = df.iloc[start:end]

            output_filename = self.output_dir+f"{base_filename}_{i + 1}.xlsx"
            chunk.to_excel(output_filename, index=False)
            print(f"Exported {output_filename}, rows: {end - start}")

    def statistic_analysis(self, method_df, mutant_df):
        print("Total classes: %s\nTotal methods: %s\nTotal mutants: %s\n" %
              (mutant_df["class"].unique().shape[0],
               mutant_df["method"].unique().shape[0],
               mutant_df.shape[0]))

        self.split_and_export_to_excel(method_df, "method_statistic")
        self.split_and_export_to_excel(mutant_df, "mutant_statistic")

    def to_long_path(self, path):
        """
        Convert a normal path to a Windows extended-length path (\?\ prefix).
        """
        # First normalize the path and convert to an absolute path
        abs_path = os.path.abspath(path)
        # If it already has the long path prefix, return directly
        if abs_path.startswith(r"\\?\\"):
            return abs_path
        abs_path = os.path.normpath(abs_path)
        # For a normal path, just add the prefix
        return r"\\?\\" + abs_path

    def delete_graphs(self, delete=False):
        """
        Optionally delete graph-related files and directories if all required files exist.
        """
        for dirpath, dirnames, filenames in os.walk(self.file_dirs, topdown=False):
            for dirname in dirnames:
                if dirname == "graph":
                    graph_path = os.path.join(dirpath, dirname)

                    files_exist = all(os.path.isfile(os.path.join(graph_path, f)) for f in self.required_files)

                    if files_exist and delete:
                        # Delete the required files
                        for file_name in self.required_files:
                            file_path = os.path.join(graph_path, file_name)
                            try:
                                os.remove(file_path)
                                print(f"Deleted file: {file_path}")
                            except Exception as e:
                                print(f"Failed to delete file {file_path}: {e}")

                        # Delete the graph directory
                        try:
                            os.rmdir(graph_path)
                            print(f"Deleted directory: {graph_path}")
                        except Exception as e:
                            print(f"Failed to delete directory {graph_path}: {e}")

                    embedding_files = ["ast_embedding.jsonl", "cfg_embedding.jsonl", "dfg_embedding.jsonl"]
                    files_exist = all(os.path.isfile(os.path.join(graph_path, f)) for f in embedding_files)

                    if files_exist and delete:
                        # Delete the embedding files
                        for file_name in embedding_files:
                            file_path = os.path.join(graph_path, file_name)
                            try:
                                os.remove(file_path)
                                print(f"Deleted file: {file_path}")
                            except Exception as e:
                                print(f"Failed to delete file {file_path}: {e}")

                        # Delete the graph directory
                        try:
                            os.rmdir(graph_path)
                            print(f"Deleted directory: {graph_path}")
                        except Exception as e:
                            print(f"Failed to delete directory {graph_path}: {e}")

    def validate_path(self, paths):
        """
        Validate whether all required graph files exist under given paths.
        """
        idxs = []
        for file_path in paths:
            basename = os.path.basename(file_path)
            if basename == "graph":
                files_exist = all(os.path.isfile(os.path.join(file_path, f)) for f in self.required_files)
                idxs += [files_exist]
        return idxs

    def get_graphs(self, mutant_df):
        """
        Compute original_graph_path and mutant_graph_path for each row
        and filter out rows where the required graph files are missing.
        """
        mutant_df["original_graph_path"] = mutant_df["file_path"].\
            apply(lambda x: self.get_parent(x, 4))  # graph under the original path
        mutant_df["mutant_graph_path"] = mutant_df["file_path"].\
            apply(lambda x: os.path.dirname(x)+"\\graph")  # graph under the mutants path

        original_arr = self.validate_path(mutant_df["original_graph_path"].values.tolist())
        mutant_arr = self.validate_path(mutant_df["mutant_graph_path"].values.tolist())
        mask = np.array(len(original_arr)*[True]) & np.array(mutant_arr)
        ans_df = mutant_df[mask]
        ans_df["mutant_id_col"] = range(len(ans_df))

        graph_num = ans_df["original_graph_path"].unique().shape[0]+ans_df["mutant_graph_path"].unique().shape[0]
        print("Total mutants: %s\nTotal graphs: %s\nOriginal graphs: %s\nMutant graphs: %s\n" %
              (mutant_df["file_path"].unique().shape[0],
               graph_num,
               ans_df["original_graph_path"].unique().shape[0],
               ans_df["original_graph_path"].shape[0]))

        self.split_and_export_to_excel(ans_df, "graph")
        return ans_df

    def get_parent(self, path, level):
        """
        Go up 'level' directory levels from the given path and construct the original/graph path.
        """
        dir_path = path
        for _ in range(level):
            dir_path = os.path.dirname(dir_path)
        method_name = path.split("\\")[-3]
        return dir_path + "\\original\\" + method_name+"\\graph"

    def run(self):
        """
        Main entry: parse logs, compute statistics, and locate graph directories.
        """
        # self.delete_graphs(delete=True)  # If AST/CFG/DFG do not meet requirements, they can be deleted.
        method_df, mutant_df = self.parse_log()
        self.statistic_analysis(method_df, mutant_df)
        graph_df = self.get_graphs(mutant_df)


if __name__ == "__main__":
    f_dirs = "../"+"testset"+"/commons-lang3-3.17.0/"
    ParseLog(f_dirs).run()
